### ISSUE TITLE
getting this error 

### ISSUE THREAD

**Issue by Sully1796376** [Slimeemils/qb-lottery#1]
[   script:qb-lottery] SCRIPT ERROR: @qb-lottery/server.lua:8: attempt to index a nil value (field '?')
[   script:qb-lottery] > fn (@qb-lottery/server.lua:8)
[   script:qb-lottery] > <unknown> (@oxmysql/dist/build.js:22252)
[   script:qb-lottery] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by Sully1796376** [comment]
the sql is in

**Comment by KrnkTV** [comment]
I have same one

**Comment by Slimeemils** [comment]
Try now. Accidentally pushed it with the thread running every 10 seconds.

**Comment by KrnkTV** [comment]
its same error is on this line local math = reset[1].day + 1

**Comment by Slimeemils** [comment]
In your database does does it say placeholder underneath the lotto column?

**Comment by KrnkTV** [comment]
its same like in readme

**Comment by KrnkTV** [comment]
![Screenshot_37](https://user-images.githubusercontent.com/82491495/217762264-b8d49194-2510-493a-9bdf-81fdef8e2a30.png)
when trying to purchase ticket and check if ticket win
![Screenshot_38](https://user-images.githubusercontent.com/82491495/217762389-de4046b8-4e7f-44b7-9872-5359d378f21b.png)
![Screenshot_39](https://user-images.githubusercontent.com/82491495/217762450-309ce1b4-fed5-4ecf-94ce-9534da9287ff.png)

**Comment by Slimeemils** [comment]
Yes, the reason you are getting the error is because under the lotto column it is supposed to say placeholder.

**Comment by KrnkTV** [comment]
Okay but how to fix it. I didnt touch it anything in script

**Comment by Slimeemils** [comment]
Insert a row into the lotterytotal table. lotto should have placeholder, total should have 0, day should have 1, and winner should have 0. Save it and you're good.

**Comment by xxUnknown13xx** [comment]
> Insert a row into the lotterytotal table. lotto should have placeholder, total should have 0, day should have 1, and winner should have 0. Save it and you're good.

Like this? 

`winner` TINYINT(4) NULL DEFAULT '0' 

?
